locals{
    common_tags={
        project_name=var.project_name
        terraform=true
        environment=var.environment
    }
    common_name="${var.project_name}-${var.environment}"
    ami_id=data.aws_ami.joindevops.id
    catalogue_sg_id=data.aws_ssm_parameter.catalogue_sg_id.value
    private_subnet_id=split(",",data.aws_ssm_parameter.private_subnet_ids.value)[0]
    private_subnet_ids=split(",",data.aws_ssm_parameter.private_subnet_ids.value)
    vpc_id=data.aws_ssm_parameter.vpc_id.value
    backend_alb_listener=data.aws_ssm_parameter.backend_alb_listener.value
 }